apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
  namespace: ffisa-dev
  labels:
    app: mi-app
    areanegocio: tecnologia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
        - name: contenedor-principal
          image: fabricioph2/curso:{{ tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: mi-configmap
            - secretRef:
                name: mi-secret
          volumeMounts:
            - name: datos
              mount: /app/data
      volumes:
        - name: datos
          persistentVolumeClaim:
            claimName: mi-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
  namespace: ffisa-dev
spec:
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap
  namespace: ffisa-dev
data:
  DATABASE: "192.168.1.1"
---
apiVersion: v1
kind: Secret
metadata:
  name: mi-secret
  namespace: ffisa-dev
type: Opaque
data:
  PASSWORD: aG9sYQ==
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa
  namespace: ffisa-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mi-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc
  namespace: ffisa-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
